<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/03/04 21:49:06

return array(
'propel' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=lvd;host=localhost',
  'username' => 'root',
  'password' => NULL,
  'name' => 'propel',
)),);
