<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2014/03/04 21:49:06
return array(

  // sfProtoculousPlugin_module_libs

  // sfProtoculousPlugin_lib

  // sfDoctrinePlugin_module_libs

  // project

  // project_model

  // application
  'myUser' => 'E:/Projet/sfprojects/lvd/apps/frontend/lib/myUser.class.php',

  // modules

  // sfDoctrinePlugin_lib
  'sfDoctrineCli' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfDoctrineConnectionListener' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfDoctrineDatabase' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfDoctrineDataRetriever' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDataRetriever.class.php',
  'sfWebDebugPanelDoctrine' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfFormDoctrine' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfFormFilterDoctrine' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfDoctrineColumn' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfDoctrineFormFilterGenerator' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfDoctrineFormGenerator' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfDoctrineGenerator' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfDoctrineLogger' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/log/sfDoctrineLogger.class.php',
  'sfDoctrinePager' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfDoctrineRecord' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfDoctrineRecordI18nFilter' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfDoctrineRecordListener' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordListener.class.php',
  'sfDoctrineRoute' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfDoctrineRouteCollection' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfDoctrineException' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfDoctrineBaseTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfDoctrineBuildAllLoadTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllLoadTask.class.php',
  'sfDoctrineBuildAllReloadTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllReloadTask.class.php',
  'sfDoctrineBuildAllReloadTestAllTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllReloadTestAllTask.class.php',
  'sfDoctrineBuildAllTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllTask.class.php',
  'sfDoctrineBuildDbTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfDoctrineBuildFiltersTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfDoctrineBuildFormsTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfDoctrineBuildModelTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfDoctrineBuildSchemaTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfDoctrineBuildSqlTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfDoctrineDumpDataTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfDoctrineLoadDataTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfDoctrineDqlTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfDoctrineDropDbTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfDoctrineGenerateAdminTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfDoctrineGenerateMigrationsDbTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfDoctrineGenerateMigrationsModelsTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfDoctrineGenerateMigrationTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfDoctrineGenerateModuleForRouteTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfDoctrineGenerateModuleTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfDoctrineInsertSqlTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfDoctrineMigrateTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfDoctrineRebuildDbTask' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineRebuildDbTask.class.php',
  'sfTesterDoctrine' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfDoctrineUniqueValidator' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfDoctrineUniqueValidator.class.php',
  'sfValidatorDoctrineChoice' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfValidatorDoctrineChoiceMany' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoiceMany.class.php',
  'sfValidatorDoctrineUnique' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfWidgetFormDoctrineChoice' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfWidgetFormDoctrineChoiceMany' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoiceMany.class.php',
  'sfWidgetFormDoctrineSelect' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineSelect.class.php',
  'sfWidgetFormDoctrineSelectMany' => 'C:/wamp/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineSelectMany.class.php',
);
